import type { Metadata } from "next";

import { cn } from "@lib/utils";
import LoginExtender from "@/components/login-extender";
import { AR_One_Sans as Font } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"

const font = Font({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="dark">
      <body className={cn(
        "min-h-screen bg-background antialiased",
        font.className,
      )}>
        <QueryClientProvider client={queryClient}>
          <LoginExtender>
            {children}
          </LoginExtender>
        </QueryClientProvider>
      </body>
    </html>
  );
}
